# Generated by Django 4.0.4 on 2022-05-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='block',
            new_name='Bairro',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cep',
            new_name='CEP',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='Cidade',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='complement',
            new_name='Complemento',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='Endereço',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uf',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='insta',
            new_name='Instagram',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='Numero',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='Telefone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discard',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
        migrations.AddField(
            model_name='user',
            name='Realiza descarte de óleo frequentemente?',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Se sim, a cada quanto tempo?',
            field=models.CharField(choices=[(False, 'Não descarto'), ('Duas semanas', 'A cada duas semanas'), ('Um mês', 'A cada um mês'), ('Dois meses', 'A cada dois meses')], default='', max_length=30),
        ),
    ]
