# Generated by Django 4.0.4 on 2022-05-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_block_user_bairro_rename_cep_user_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Se sim, a cada quanto tempo?',
            field=models.CharField(choices=[('Não descarta', 'Não descarto'), ('Duas semanas', 'A cada duas semanas'), ('Um mês', 'A cada um mês'), ('Dois meses', 'A cada dois meses')], default='', max_length=30),
        ),
    ]
