# Generated by Django 4.0.4 on 2022-05-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Telefone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
