# Generated by Django 4.0.4 on 2022-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Bairro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Cidade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Complemento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Completo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Endereço',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Realiza descarte de óleo frequentemente?',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Se sim, a cada quanto tempo?',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Telefone',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.CharField(default='', max_length=30, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=30, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='user',
            name='descard',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Realiza descarte de óleo frequentemente?'),
        ),
        migrations.AddField(
            model_name='user',
            name='full',
            field=models.BooleanField(default=False, verbose_name='Completo'),
        ),
        migrations.AddField(
            model_name='user',
            name='insta',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default='', max_length=10, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=14, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.CharField(choices=[('Não descarta', 'Não descarto'), ('Duas semanas', 'A cada duas semanas'), ('Um mês', 'A cada um mês'), ('Dois meses', 'A cada dois meses')], default='', max_length=30, verbose_name='Se sim, a cada quanto tempo?'),
        ),
        migrations.AddField(
            model_name='user',
            name='uf',
            field=models.CharField(default='', max_length=20, verbose_name='Estado'),
        ),
    ]
