# Generated by Django 4.0.4 on 2022-06-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_bairro_remove_user_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descard',
            field=models.BooleanField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default=False, verbose_name='Realiza descarte de óleo frequentemente?'),
        ),
    ]
