# Generated by Django 4.0.4 on 2022-06-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_descard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descard',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='', max_length=3, verbose_name='Realiza descarte de óleo frequentemente?'),
        ),
    ]
