# Generated by Django 4.0.4 on 2022-06-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_descard_remove_user_time_user_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='teste'),
        ),
    ]
