# Generated by Django 4.0.4 on 2022-06-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nome ou razão social'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name='Sobrenome ou nome fantasia'),
        ),
    ]
