# Generated by Django 4.0.4 on 2022-06-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liters',
            field=models.IntegerField(default=0, verbose_name='Média de óleo utilzado por mês(Lts)'),
        ),
    ]
