# Generated by Django 4.0.4 on 2022-06-03 22:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='teste',
        ),
        migrations.AddField(
            model_name='collect',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='collect',
            name='block',
            field=models.CharField(default='', max_length=30, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='collect',
            name='cep',
            field=models.CharField(default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='collect',
            name='city',
            field=models.CharField(default='', max_length=30, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='collect',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='collect',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data da coleta'),
        ),
        migrations.AddField(
            model_name='collect',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Foto do recipiente com o óleo'),
        ),
        migrations.AddField(
            model_name='collect',
            name='liters',
            field=models.IntegerField(default=0, verbose_name='Quantidade aproximada de óleo (Lts)'),
        ),
        migrations.AddField(
            model_name='collect',
            name='number',
            field=models.CharField(default='', max_length=10, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='collect',
            name='uf',
            field=models.CharField(default='', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='collect',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
