# Generated by Django 4.0.4 on 2022-06-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='img',
            field=models.ImageField(default='', upload_to='', verbose_name='Foto do recipiente com o óleo'),
        ),
    ]
