# Generated by Django 4.0.4 on 2022-06-03 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_collect_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
