# Generated by Django 4.0.4 on 2022-06-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_remove_collect_teste_collect_address_collect_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='date',
        ),
    ]
