# Generated by Django 4.0.4 on 2022-06-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_collect_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='status',
            field=models.CharField(choices=[('teste', 'teste'), ('teste2', ''), ('', 'teste3')], default='', max_length=20),
        ),
    ]
