# Generated by Django 4.0.4 on 2022-06-02 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_remove_collect_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='first_name',
        ),
        migrations.AddField(
            model_name='collect',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data da coleta'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Foto do recipiente com o óleo'),
        ),
    ]
