# Generated by Django 4.0.4 on 2022-06-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_collect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='obs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='collect',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada'), ('Concluida', 'Concluida'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=10),
        ),
    ]
