# Generated by Django 4.0.4 on 2022-06-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_collect_obs_alter_collect_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='username',
            new_name='first_name',
        ),
    ]
