# Generated by Django 4.0.4 on 2022-06-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0007_rename_username_collect_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='first_name',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='collect',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
