# Generated by Django 4.0.4 on 2022-06-04 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collect', '0008_rename_first_name_collect_user_id_collect_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='collect',
            name='id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
