# Generated by Django 4.0.4 on 2022-06-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0011_collect_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='time',
            field=models.CharField(choices=[('morning', '8:00hrs - 12:00hrs'), ('afternon', '13:00hrs - 18:00hrs')], default='', max_length=10, verbose_name='Horario da coleta'),
        ),
    ]
