# Generated by Django 4.0.4 on 2022-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0013_alter_collect_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='img',
            field=models.ImageField(default='', upload_to='media', verbose_name='Foto do recipiente com o óleo'),
        ),
    ]
