# Generated by Django 4.0.4 on 2022-06-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0015_alter_collect_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='real_liters',
            field=models.FloatField(default=0, verbose_name='Quantidade real de óleo (Lts)'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='time',
            field=models.CharField(choices=[('8:00hrs - 12:00hrs', '8:00hrs - 12:00hrs'), ('13:00hrs - 18:00hrs', '13:00hrs - 18:00hrs')], default='', max_length=20, verbose_name='Horario da coleta'),
        ),
    ]
