# Generated by Django 4.0.4 on 2022-06-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0018_alter_collect_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='collect', verbose_name='Foto do recipiente com o óleo'),
        ),
    ]
