# Generated by Django 4.0.4 on 2022-06-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0020_alter_collect_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='date',
            field=models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('SAB', 'Sabado')], default='', max_length=10, verbose_name='Melhor dia da semana para realizar a coleta'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
